import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Blaze Mart | Profile ',
    description: 'Generated by create next app',
}

function page() {



    return (
        <div>

        </div>
    )
}

export default page
